@startuml
!theme toy

title Software Architect Concept (PL level)

skinparam componentStyle uml1

node "<<Computer>>" as computer {
	node "<<OS Windows, OS Linux>>" {
	  node "<<Web-browser>>" {
		  component [ *.js(React)]
	  }
	}
}

interface KeyBoard 
interface ComputerMouse

KeyBoard - computer
ComputerMouse - computer

@enduml
