@startuml
!theme toy
hide circle
title UML-ConceptClasses

Class Користувач{
    Ім'я
    Email
    Пароль
}

Class "План освітлення"{
    Назва
    Аналіз потреб
    Параметри
    План виконання робіт
    Використаний шаблон
    Використана інформація
}

Class "Шаблон плану освітлення"{
    Назва
    Опис шаблону
    Аналіз потреб
    Параметри
    План виконання робіт
}

Користувач"1" --> "0...*""План освітлення": Налаштовує

"Шаблон плану освітлення""1" --> "0...*""План освітлення": "Використовується для створення"

@enduml
